# WorldStream settings file.
# DO NOT use tabs or single quotes in this file! YAML hates these and the plugin will crash!

chunk-write-interval: 0
  # Enter an interval in seconds
  # Enter 0 for realtime (on a block update)
  # Enter -1 to disable (export on command only)
auto-export-scope: "CHUNK"
  # CHUNK = writes the current chunk (recommended)
  # LOADED = writes all loaded chunks (only use if you have something moving i.e. doors)
  # MAP = writes entire map (SLOW - avoid unless you have a beefy computer!)
enable-http-server: false
http-server-port: 80
enable-websocket-stream: false
websocket-port: 80
export-partial-blocks: false
export-decoration-blocks: false
export-entities: false
export-covered-blocks: false
  # Default to false. Set to true to export all blocks, even if theyve got an adjacent block on all sides.